### ISSUE TITLE
Build for Mac Catalyst?

### ISSUE THREAD

**Issue by GameParrot** [kbinani/je2be-ios#1]
Would it be possible to build this for macOS using Mac Catalyst and put it on the Mac App Store?  I can confirm that it is possible to build the project using Mac Catalyst with minimal modifications.

**Comment by kbinani** [comment]
I think it's possible, but I think it's better to ship [je2be-desktop](https://github.com/kbinani/je2be-desktop) as macOS edition in the AppStore.
Because je2be-ios has a mobile-specific user interface.
